version: '3.8'

services:
    meilisearch:
        image: getmeili/meilisearch
        ports:
            - "7700:7700"
        #environment:
            #MEILI_MASTER_KEY: hello
        volumes:
            - meilisearch:/data.ms

volumes:
    meilisearch:
